repos:
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.88.35
    hooks:
      - id: trufflehog
        name: Trufflehog
        description: Detect secrets in our data
        args: ["--only-verified"]
        stages: ['pre-commit']
