repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c "docker run -v './:/workdir' -i --rm trufflesecurity/trufflehog:latest git file:///workdir --since-commit HEAD --results=unverified,unknown,verified --fail --exclude-globs=CHANGELOG.md"
        language: system
        stages: ["pre-commit"]
