# Posts a PR comment with coverage results
name: Post coverage comment

on:
  workflow_run:
    workflows: ["PR atmos_validation"]
    types:
      - completed

jobs:
  coverage:
    name: Publish coverage
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Post comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
