on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.PAT }}
          release-type: python
          package-name: release-please-action
          changelog-types: >
            [{"type":"feat","section":"Features","hidden":false},
            {"type":"fix","section":"Bug Fixes","hidden":false},
            {"type":"docs","section":"Documentation","hidden":false},
            {"type":"style", "section":"Other","hidden":false},
            {"type":"refactor", "section":"Refactor","hidden":false},
            {"type":"perf", "section":"Optimization","hidden":false},
            {"type":"test", "section":"Other","hidden":false},
            {"type":"ci", "section":"CI/CD","hidden":false},
            {"type":"chore", "section":"Other","hidden":false},
            {"type":"revert", "section":"Other","hidden":false}]
            {"type":"build", "section":"Other","hidden":false}]
